networks:
  giftbox.net:
    driver: bridge
services:
  #service serveur web+php
  php:
    image: canals/php:latest
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./shared/img:/var/www/html/img
    working_dir: /var/www/src
    ports:
      - "3080:80"
    networks:
      - giftbox.net

  #Service serveur sql mariadb
  sql:
    image: mariadb:latest

    #/!\ Requiert un fichier .env avec les variables suivantes:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3380:3306"
    networks:
      giftbox.net:
        aliases:
          - giftbox.db
  adminer:
    image: adminer:latest
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - "3333:8080"
    networks:
      - giftbox.net

